name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Build release binary
        run: cargo build --release --verbose
      
      - name: Get tag name
        id: tag_name
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_name.outputs.TAG }}
          name: Release ${{ steps.tag_name.outputs.TAG }}
          draft: false
          prerelease: false
          files: |
            target/release/rsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
